# Generated by Django 3.2.6 on 2021-08-30 02:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_died', models.BooleanField(default=False)),
                ('balance', models.FloatField(null=True)),
                ('picture', models.CharField(max_length=1024)),
                ('age', models.IntegerField()),
                ('eye_color', models.CharField(choices=[('blue', 'blue'), ('brown', 'brown')], max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=1024)),
                ('about', models.CharField(max_length=1024)),
                ('registered', models.DateTimeField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('greeting', models.CharField(max_length=1024)),
                ('fruits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('vegetables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('guid', models.UUIDField()),
                ('_id', models.CharField(max_length=124)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.company')),
                ('friends', models.ManyToManyField(related_name='_person_person_friends_+', to='person.Person')),
            ],
        ),
    ]
